name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> .env
          echo "FLASK_API_URL=${{ secrets.FLASK_API_URL }}" >> .env
          echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> .env
          echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> .env
          echo "AZURE_GPT4_DEPLOYMENT=${{ secrets.AZURE_GPT4_DEPLOYMENT }}" >> .env
          echo "AZURE_WHISPER_DEPLOYMENT=${{ secrets.AZURE_WHISPER_DEPLOYMENT }}" >> .env
          echo "AZURE_TTS_DEPLOYMENT=${{ secrets.AZURE_TTS_DEPLOYMENT }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker tags
        id: tags
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tags=${{ secrets.DOCKER_USERNAME }}/mindmend-backend:${{ github.ref_name }},${{ secrets.DOCKER_USERNAME }}/mindmend-backend:latest" >> $GITHUB_ENV
          else
            echo "tags=${{ secrets.DOCKER_USERNAME }}/mindmend-backend:latest" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{ env.tags }}
          outputs: type=docker, dest=/tmp/image.tar

      - name: Load image for scanning
        run: |
          docker load --input /tmp/image.tar
          docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/mindmend-backend:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          # exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Docker container
        run: |
          docker run -d --name mindmend-backend-test ${{ secrets.DOCKER_USERNAME }}/mindmend-backend:latest

      - name: Wait for Docker container to start
        run: |
          sleep 30
          docker ps -a | grep mindmend-backend-test || exit 1

      - name: Stop and remove Docker container
        run: |
          docker stop mindmend-backend-test
          docker rm mindmend-backend-test

      - name: Log out from Docker Hub
        run: docker logout